Review changes

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -1,15 +1,31 @@
-on: 
+name: "Trigger Integration tests"
+on:
+  push:
+    branches:
+      - master
+      - 'releases/*'
   pull_request:
     branches:
-      - '*'
+      - master
+      - 'releases/*'
 jobs: 
     trigger-integration-tests:
       name: Trigger Integration tests
       runs-on: ubuntu-latest
       steps:
+        - name: Extract branch name
+          id: extract_branch
+          run: |
+            value="##[set-output name=branchname;]$(echo ${GITHUB_REF##*/})"
+            echo ">> $value"
+
         - name: Trigger Test run
-          env:
-           repname: ${env:GITHUB_REPOSITORY};
-          run: | 
-           curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/rgsubh/l2-integration-tests/dispatches --data '{"event_type": "K8sCreateSecret", "client_payload": {"action": "CreateSecret", "commit": "${{ github.sha }}", "branch": "${{ github.event.pull_request.base.ref }}", "PR_NUMBER": "${{ github.event.pull_request.number }}", "GITHUB_REPOSITORY":  "rgsubh/k8s-create-secret" }}'
-  
+          if: github.event.pull_request.base.ref == 'releases/v1' || steps.extract_branch.outputs.branchname == 'releases/v1' || github.event.pull_request.base.ref == 'master' || steps.extract_branch.outputs.branchname == 'master'
+          run: |
+           response=$(curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/Azure/azure-actions-integration-tests/dispatches --data '{"event_type": "K8sCreateSecretReleasesPR", "client_payload": {"action": "CreateSecret", "commit": "${{ github.event.pull_request.head.sha }}", "repository":  "${{ github.repository }}", "prNumber": "${{ github.event.pull_request.number }}", "tobranch": "${{ github.event.pull_request.base.ref }}",  "frombranch": "${{ github.event.pull_request.head.ref }}" }}')
+           if [ "$response" == "" ]; then 
+            echo "Integration tests triggered successfully"; 
+           else 
+            echo "Triggering integration tests failed with: '$response'";
+            exit 1;
+           fi
