changes

diff --git a/.github/workflows/intergation-tests.yml b/.github/workflows/intergation-tests.yml
--- a/.github/workflows/intergation-tests.yml
+++ b/.github/workflows/intergation-tests.yml
@@ -13,10 +13,9 @@ jobs:
       name: Trigger Integration tests
       runs-on: ubuntu-latest
       steps:
-        - name: Trigger Test run
+        - name: Trigger Test run for PR
           if: github.event.pull_request.base.ref == 'releases/v1' || github.event.pull_request.base.ref == 'master'
           run: |
-           echo ${{github.ref}}
            response=$(curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/rgsubh/l2-integration-tests/dispatches --data '{"event_type": "K8sCreateSecretReleasesPR", "client_payload": {"action": "CreateSecret", "commit": "${{ github.event.pull_request.head.sha }}", "repository":  "${{ github.repository }}", "prNumber": "${{ github.event.pull_request.number }}", "tobranch": "${{ github.event.pull_request.base.ref }}",  "frombranch": "${{ github.event.pull_request.head.ref }}", "token": "${{ secrets.GITHUB_TOKEN }}" }}')
            if [ "$response" == "" ]; then 
             echo "Integration tests triggered successfully"; 
@@ -24,8 +23,14 @@ jobs:
             echo "Triggering integration tests failed with: '$response'";
             exit 1;
            fi
-        - name: always
-          if: ${{ always() }} 
+        - name: Trigger Test run for PUSH
+          if: github.ref == 'refs/heads/releases/v1'
           run: |
-              echo ${{github.ref}}
+            response=$(curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/rgsubh/l2-integration-tests/dispatches --data '{"event_type": "K8sCreateSecretReleasesPush", "client_payload": {"action": "CreateSecret", "commit": "${{ github.event.pull_request.head.sha }}", "repository":  "${{ github.repository }}", "prNumber": "${{ github.event.pull_request.number }}", "tobranch": "${{ github.event.pull_request.base.ref }}",  "frombranch": "${{ github.event.pull_request.head.ref }}", "token": "${{ secrets.GITHUB_TOKEN }}" }}')
+            if [ "$response" == "" ]; then 
+              echo "Integration tests triggered successfully"; 
+            else 
+              echo "Triggering integration tests failed with: '$response'";
+              exit 1;
+            fi
  
