Updating repo name

diff --git a/.github/workflows/intergation-tests.yml b/.github/workflows/intergation-tests.yml
--- a/.github/workflows/intergation-tests.yml
+++ b/.github/workflows/intergation-tests.yml
@@ -23,29 +23,14 @@ jobs:
           env:
             test1: ${{ github.event.pull_request.head.sha }}
           run: |
-           cat <<EOF
-            generate_post_data(){
-            {
-              "event_type": "K8sCreateSecretReleasesPR",
-              "client_payload": {
-                "commit": "${{ github.event.pull_request.head.sha }}",
-                "repository": "${{ github.repository }}",
-                "prNumber": "${{ github.event.pull_request.number }}",
-                "tobranch": "${{ github.event.pull_request.base.ref }}",
-                "frombranch": "${{ github.event.pull_request.head.ref }}",
-                "token": "${{ secrets.GITHUB_TOKEN }}"
-              }
-            }
-            }
-            EOF
-            test=${github.event.pull_request.head.sha}
+            test=${{github.event.pull_request.head.sha}}
             echo ">> '$test'"
-           response=$(curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/rgsubh/l2-integration-tests/dispatches --data "$(generate_post_data)" )
-           if [ "$response" == "" ]; then 
-            echo "Integration tests triggered successfully"; 
-           else 
-            echo "Triggering integration tests failed with: '$response'";
-            exit 1;
-           fi
+            response=$(curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/rgsubh/l2-integration-tests/dispatches --data "$(generate_post_data)" )
+            if [ "$response" == "" ]; then 
+              echo "Integration tests triggered successfully"; 
+            else 
+              echo "Triggering integration tests failed with: '$response'";
+              exit 1;
+            fi
         
      
